version: "3"
services:
  db-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: V6-DB
  app:
    image: my-app
    ports:
      - 13000:3000
